USE [master]
GO

/****** Object:  Database [mini_market_system]    Script Date: 6/14/2023 10:43:03 AM ******/
CREATE DATABASE [mini_market_system]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'mini_market_system', FILENAME = N'F:\new folder\MSSQL12.FAHAD\MSSQL\DATA\mini_market_system.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'mini_market_system_log', FILENAME = N'F:\new folder\MSSQL12.FAHAD\MSSQL\DATA\mini_market_system_log.ldf' , SIZE = 816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [mini_market_system] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [mini_market_system].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [mini_market_system] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [mini_market_system] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [mini_market_system] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [mini_market_system] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [mini_market_system] SET ARITHABORT OFF 
GO

ALTER DATABASE [mini_market_system] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [mini_market_system] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [mini_market_system] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [mini_market_system] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [mini_market_system] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [mini_market_system] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [mini_market_system] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [mini_market_system] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [mini_market_system] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [mini_market_system] SET  ENABLE_BROKER 
GO

ALTER DATABASE [mini_market_system] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [mini_market_system] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [mini_market_system] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [mini_market_system] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [mini_market_system] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [mini_market_system] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [mini_market_system] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [mini_market_system] SET RECOVERY FULL 
GO

ALTER DATABASE [mini_market_system] SET  MULTI_USER 
GO

ALTER DATABASE [mini_market_system] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [mini_market_system] SET DB_CHAINING OFF 
GO

ALTER DATABASE [mini_market_system] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [mini_market_system] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [mini_market_system] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [mini_market_system] SET  READ_WRITE 
GO

